[workspace]
members = ["cargo:crates/bridle"]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.3"
# Skip checking whether the specified configuration files are up to date
allow-dirty = ["ci"]
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell", "npm", "homebrew"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "aarch64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Where to host releases
hosting = "github"
# Whether to install an updater program
install-updater = false
# A GitHub repo to push Homebrew formulas to
tap = "neiii/homebrew-bridle"
# Customize the Homebrew formula name
formula = "bridle"
# Publish jobs to run in CI
publish-jobs = ["homebrew", "npm"]
# The npm package should have this name
npm-package = "bridle-ai"
